import PropTypes from 'prop-types';

export const Column = {};

Column.propTypes = {
  body: PropTypes.any,
  bodyClassName: PropTypes.string,
  bodyStyle: PropTypes.object,
  className: PropTypes.string,
  colSpan: PropTypes.number,
  columnKey: PropTypes.string,
  editor: PropTypes.func,
  editorValidator: PropTypes.func,
  editorValidatorEvent: PropTypes.string,
  excludeGlobalFilter: PropTypes.bool,
  expander: PropTypes.bool,
  exportable: PropTypes.bool,
  field: PropTypes.string,
  filter: PropTypes.bool,
  filterElement: PropTypes.object,
  filterField: PropTypes.string,
  filterFunction: PropTypes.func,
  filterHeaderClassName: PropTypes.string,
  filterHeaderStyle: PropTypes.object,
  filterMatchMode: PropTypes.string,
  filterMaxLength: PropTypes.number,
  filterPlaceholder: PropTypes.string,
  filterType: PropTypes.string,
  footer: PropTypes.any,
  footerClassName: PropTypes.string,
  footerStyle: PropTypes.object,
  frozen: PropTypes.bool,
  header: PropTypes.any,
  headerClassName: PropTypes.string,
  headerStyle: PropTypes.object,
  loadingBody: PropTypes.func,
  onEditorCancel: PropTypes.func,
  onEditorSubmit: PropTypes.func,
  reorderable: PropTypes.bool,
  rowEditor: PropTypes.bool,
  rowReorder: PropTypes.bool,
  rowReorderIcon: PropTypes.string,
  rowSpan: PropTypes.number,
  selectionMode: PropTypes.string,
  sortable: PropTypes.any,
  sortField: PropTypes.string,
  sortFunction: PropTypes.func,
  style: PropTypes.object
};

Column.defaultProps = {
  body: null,
  bodyClassName: null,
  bodyStyle: null,
  className: null,
  colSpan: null,
  columnKey: null,
  editor: null,
  editorValidator: null,
  editorValidatorEvent: 'click',
  excludeGlobalFilter: false,
  expander: false,
  exportable: true,
  field: null,
  filter: false,
  filterElement: null,
  filterField: null,
  filterFunction: null,
  filterHeaderClassName: null,
  filterHeaderStyle: null,
  filterMatchMode: 'startsWith',
  filterMaxLength: null,
  filterPlaceholder: null,
  filterType: 'text',
  footer: null,
  footerClassName: null,
  footerStyle: null,
  frozen: false,
  header: null,
  headerClassName: null,
  headerStyle: null,
  loadingBody: null,
  onEditorCancel: null,
  onEditorSubmit: null,
  reorderable: true,
  rowEditor: false,
  rowReorder: false,
  rowReorderIcon: 'pi pi-bars',
  rowSpan: null,
  selectionMode: null,
  sortable: false,
  sortField: null,
  sortFunction: null,
  style: null
};
